[workspace]
members = [
    "flash-lib",
    "flash-cli",
    "flash-df",
    "flash-wasm",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1"

[patch.crates-io]
flash-lib = { path = "flash-lib" }
